config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :pics do
      member do
        put "like", to: "pics#upvote"
      end
    end
    
    root 'pics#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
    acts_as_votable
    belongs_to :user
    
  has_attached_file :image, styles: { medium: "300x300>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
    before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
    before_action :authenticate_user!, except: [:index,:show]
    
    def index
        @pics = Pic.all.order('created_at DESC')
    end
    
    def show
        
    end
    
    def new
        @pic = current_user.pics.build
    end
    
    def create
        @pic = current_user.pics.build(pic_params)
        if @pic.save
            redirect_to @pic, notice: "Saved!"
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @pic.update(pic_params)
            redirect_to @pic, notice: "Updated!"
        else
            render 'edit'
        end
    end
    
    def destroy
        @pic.destroy
        redirect_to root_path
    end
    
    def upvote
        @pic.upvote_by current_user
        redirect_to request.referer
    end
    
    private
    def pic_params
        params.require(:pic).permit(:title, :description, :image)
    end
    
    def find_pic
        @pic = Pic.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic, html:{multipart: true} do |f| %>
<% if @pic.errors.any? %>
<%= plurarize(@pic.errors.count, 'error') %>
<% @pic.errors.full_messages.each do |msg| %>
<%= msg %>
<% end %>
<% end %>
<div class="form-group">
<%= f.input :image, input_html: {class: 'form-control'} %>
</div>
<div class="form-group">
<%= f.input :title, input_html: {class: 'form-control'} %>
</div>
<div class="form-group">
<%= f.input :description, input_html: {class: 'form-control'} %>
</div>
<%= f.button :submit, class: 'btn btn-info' %>
<% end %>

app/views/pics/edit.html.erb
<h1>Edit Pic</h1>
<%= image_tag(@pic.image.url(:medium)) %>

<%= render 'form' %>

<%= link_to 'Cancel', pic_path %>

app/views/pics/index.html.erb
<h1>Placeholder!</h1>

<% @pics.each do |pic| %>
<%= link_to (image_tag pic.image.url(:medium)), pic %>
<%= link_to pic.title, pic%><br>
<% end %>
<br><br>
<%= link_to 'New', new_pic_path %>

app/views/pics/new.html.erb
<h1>Post Pic</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/pics/show.html.erb
<%= image_tag(@pic.image.url(:medium)) %>
<h1><%= @pic.title %></h1>
<p><%= @pic.description %></p>
<p><%= @pic.user.email %></p>

<%= link_to 'like '+ @pic.get_upvotes.size.to_s, like_pic_path(@pic), method: :put, class:"btn btn-default" %>

<%= link_to 'Back', root_path %>
<%= link_to 'Edit', edit_pic_path %>
<%= link_to 'Delete', pic_path, method: :delete, data: {confirm: "Sure?"} %>